# Generated by Django 4.1 on 2023-11-26 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="MainCategory",
        ),
    ]
