# Generated by Django 4.1 on 2023-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_rename_category_maincategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                null=True,
                upload_to="website/post_images/",
            ),
        ),
    ]
