# Generated by Django 4.1 on 2023-11-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="default_image.jpg", null=True, upload_to="img/"
            ),
        ),
    ]
