# Generated by Django 4.1 on 2023-11-30 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
