# Generated by Django 4.1 on 2023-12-01 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_rename_user_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
