# Generated by Django 4.1 on 2023-12-03 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0018_like_delete_userlike"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
